# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d02ca3d300c68193245862b7ef39254ce6cb744e8f51d27876eb83bf30d5b7babac332d0aa35ba43e45302a6c9592dfb8467e54a985ade40d3b0b0a6549166d

test:
  secret_key_base: fe0d563a831fb2486fb6ba8d9db1923d36e79d97cb329c556020b7a4921aae8e676ede84985e709e266dc8536c77b6b217ec11ee8ae2df5cc1101a027b7fb97a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
